### ISSUE TITLE
Todos from beta-test

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh#46]
* [x] names for jobs, see #49
* [x] year in timeseries plot not 1970
* [x] hoverinfo in stacked plots round to only one digit
* [x] bezeichnung rd rdeck einheitlich
* [x] stacked result entweder in production umbenennen oder import/export/demand einfügen
* [x] result co2 wurde bei vielen nicht angezeigt
* [x] einheiten wie MW einfügen, z.B. bei heatplot
* [x] result timeseries (flow) timeseries plot: nur auswahl/umbenennen
* [x] jahresübersicht kennzeichnen in timeseries chron plots, oben unten (cswh)
* [x] db connection anzahl überprüfen, see #47 
* [x] demand als line in stacked result anzeigen
* [x] nms hub results etc. extra behandeln, da dort nichts produziert wird
* [x] bei scenario update auf confirm warten
* [x] wochentage bei xaxis (simnh)
* [x] Render a plot when landing on Tab by default (stacked and hub plots)
* [x] hide result tabs when result not available
* [x] Labels instead of 'ids' in summery table
* [x] Reload scenario overview automatically when scenario is imported 
* [x] Delete button response with modal instead of javascript prompt
* [x] Remove Modal when landing on edit scenario page??? (Kind of annoying, rather move info to help)
* [x] Improve/correct Kiel Heat Stacked Input 'no-data-to render' handling
* [x] Discard changes
* [x] Scenario Description in Overview Table 
* [x] Label instead of id in scenario input overvie plot when hovering on it

**Comment by simnh** [comment]
Should we add import/export to stacked result plot?

**Comment by simnh** [comment]
linked to #49
